### ISSUE TITLE
Read rust-toolchain.toml file

### ISSUE THREAD

**Issue by lcswillems** [dtolnay/rust-toolchain#116]
Does the action take into account the `rust-toolchain.toml` of the repository?

**Comment by dtolnay** [comment]
It does not look at rust-toolchain.toml.

**Comment by lcswillems** [comment]
Would it be possible to make it look at the rust-toolchain.toml file?

**Comment by luigi311** [comment]
Can this be made to read rust-toolchain.toml that way we only need to change the toolchain version in one location and not in the toml and github workflow file?

**Comment by Bnyro** [comment]
Fyi, you can extract the Rust toolchain version yourself using a TOML parser, e.g. `yq`:
```yaml
      - name: Extract Toolchain version from rust-toolchain.toml
        id: extract-toolchain-version
        uses: mikefarah/yq@v4
        with:
          cmd: yq '.toolchain.channel' rust-toolchain.toml

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.extract-toolchain-version.outputs.result }}
```

Not as convenient as it could be, but fine as a workaround for now.
