### ISSUE TITLE
Odd rustup check behavior depending on precise action used

### ISSUE THREAD

**Issue by Tomer-Eliahu** [dtolnay/rust-toolchain#125]
Depending on which version of the action you use you get different rustup check results.

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout #Clones the repository to the runner
      uses: actions/checkout@v4

      #uninstall stable rust (GitHub runners come with latest stable rust installed).
    - shell: bash
      run: rustup toolchain uninstall stable
      
    - name: rustup_toolchain_install
      uses: dtolnay/rust-toolchain@1.81

      #Run rustup check
    - shell: pwsh
      run: rustup check
```

yields: 
<img width="469" alt="image" src="https://github.com/user-attachments/assets/6cbc5e14-88e4-43b2-8210-a581f9623b29">

However running:

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout #Clones the repository to the runner
      uses: actions/checkout@v4

      #uninstall stable rust (GitHub runners come with latest stable rust installed).
    - shell: bash
      run: rustup toolchain uninstall stable

    - name: rustup_toolchain_install
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.81

      #Run rustup check
    - shell: pwsh
      run: rustup check
```

yields:

<img width="466" alt="image" src="https://github.com/user-attachments/assets/28e74666-78bd-4008-839d-de1810c23de1">

So only using  
```yml
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.81
```
yields the expected rustup check outcome.
