### ISSUE TITLE
rust-toolchain.toml support

### ISSUE THREAD

**Issue by stepancheg** [dtolnay/rust-toolchain#133]
[Some projects](https://github.com/facebook/buck2/blob/87224d7adb3e5ed5885629ef0f29e8a74e3b6a77/.github/actions/setup_linux_env/action.yml#L6-L14) use this pattern to install the toolchain specified in `rust-toolchain.toml`:

```
  - uses: SebRollen/toml-action@v1.2.0
    id: read_rust_toolchain
    with:
      file: rust-toolchain
      field: toolchain.channel
  - uses: dtolnay/rust-toolchain@v1
    with:
      toolchain: ${{ steps.read_rust_toolchain.outputs.value }}
      components: clippy
```

Would be nice if `dtolnay/rust-toolchain` action supported this out of the box.

**Comment by dtolnay** [comment]
I would prefer not to support it in this action. But someone else could maintain a different action that provides that pair of steps as one action.

**Comment by stepancheg** [comment]
I didn't mean to call `SebRollen/toml-action`. Instead, `dtolnay/rust-toolchain` action could just install `rustup`, and then rust call `cargo` without arguments or something to make `rustup` download the toolchain.

Still object?

**Comment by net** [comment]
I assumed this action would use rust-toolchain.toml, and was surprised to find it didn't.

**Comment by dtolnay** [comment]
In my projects my preference has been that the workflow yml file is the source of truth about the CI compiler version. There is room for an action that uses a different source of truth but that isn't this action. The readme is clear, both in the "Example workflow" section and "Inputs" section, about how the toolchain version is selected.

**Comment by net** [comment]
I do not think the readme is clear at all.

> This GitHub Action installs a Rust toolchain using rustup. It is designed for one-line concise usage and good defaults.

Both "installs a Rust toolchain using rustup" and "one-line concise usage" suggest to me that it will read rustrust-toolchain.toml unless overridden, like rustup does by default.

What is the point of having a rust-toolchain.toml file if it's not the source of truth?

At the very least, the readme would benefit from a clear, explicit, warning that dtolnay/rust-toolchain ignores rust-toolchain.toml.

**Comment by net** [comment]
My specific issue was with targets not being read from our rust-toolchain.toml. I agree that the readme is reasonably clear how the `toolchain` version itself is determined, although I can see others still being surprised by that.

**Comment by net** [comment]
What if there was an @rev, like dtolnay/rust-toolchain@with-infer, that took no inputs and executed rustup without any overrides?

**Comment by dtolnay** [comment]
https://github.com/dtolnay/rust-toolchain/issues/133#issuecomment-2591318675

**Comment by dtolnay** [comment]
I guess I'll say for the third time: make a different action. It is not a goal that you or anyone else be able to use this action. It does the things I need, and is generally usable outside of my projects too, but there is a limited extent to which I am interested in taking feature requests.

**Comment by net** [comment]
Would you accept a reasonable PR making the readme clearer that rust-toolchain.toml is ignored?

**Comment by stepancheg** [comment]
> someone else could maintain a different action that provides...

Hey @dtolnay I'd like to post another reason for having this feature in this repository.

I think `rust-toolchain.toml` practically mostly used in private repositories, not in open-source projects. In such projects, only actions from trusted people and organisation should be used, otherwise it is too easy to leak company secrets.

So if me, or @net would create a repository with such action that uses `rust-toolchain.toml`, it will be two stars project not used by anyone who cares about security (technically one can use precise revision number, but that is too much trouble). So practically it is either here, or nowhere.

As a side note, I think Rust Foundation should actually own such and similar actions.

There's an interesting company, Astral, who tries to be Cargo for Python. They are making `uv` (package manager for Python), `ruff` (`rustfmt` for Python), portable python dist and among other things:
- https://github.com/astral-sh/ruff-pre-commit — pre-commit hook to run ruff
- https://github.com/astral-sh/ruff-action — github action to format/typecheck python
- https://github.com/astral-sh/uv-pre-commit — pre-commit hook for various uv stuff
- https://github.com/astral-sh/setup-uv — github action to set up uv
  - this one is similar to this rust-toolchain action, and it allows specifying version explicitly like this action, or it can read from `uv.toml` or `pyproject.toml`

Would be nice to have these but for Rust somewhere.

If you are still not convinced, fine.

**Comment by mkroening** [comment]
FWIW, I have a two-star action that does this and is easy to audit (it uses this action for the actual installing): https://github.com/mkroening/rust-toolchain-toml

**Comment by net** [comment]
Ideally the action wouldn't need to parse rust-toolchain.toml itself; simply running `rustup show` in a directory with a rust-toolchain.toml should use the rust-toolchain.toml (and rustup 1.28, when released, will use rust-toolchain.toml when `rustup toolchain install` is run without an explicit toolchain specified).

**Comment by net** [comment]
I just realized GitHub action runners already have `rustup` pre-installed, so this action isn't even needed!

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Only needed if your action will run two or more rust
      # commands concurrently, otherwise rustup will lazily 
      # install your rust-toolchain.toml when needed:
      - name: 'Install from rust-toolchain.toml'
        run: rustup show
```

This will install your `rust-toolchain.toml`.
