### ISSUE TITLE
Using @master then adding toolchain field to nightly does not work

### ISSUE THREAD

**Issue by ffimnsr** [dtolnay/rust-toolchain#138]
According to the `README.md` documentation, in order to specify a particular toolchain using the `toolchain` field, I need to use the `@master` revision.

Here's my config:

```yaml
... some config here ...
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustc-dev
      - name: Run cargo check tool
        run: cargo check --all-targets --all-features --tests --benches --release --verbose
... some config here ...
```

Despite configuring the toolchain to use `nightly` in the setup mentioned above, Cargo continues to default to the `stable` toolchain. This issue persists even though the toolchain field has been explicitly set to `nightly` in the configuration.

---

Currently, my workaround involves adhering to the documentation by specifying the `@rev`, particularly the `@nightly` version in github action, in my GitHub workflow configuration.
