### ISSUE TITLE
The action does not install aarch64-unknown-linux-gnu on ubuntu-22.04

### ISSUE THREAD

**Issue by kkew3** [dtolnay/rust-toolchain#140]
My workflow (minimal reproducible example) is:

```yaml
runs-on: ubuntu-22.04
steps:
  - name: Install ARM compiler toolchain
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu libc6-dev-arm64-cross
  - uses: dtolnay/rust-toolchain@stable
    with:
      target: aarch64-unknown-linux-gnu
      toolchain: stable
  - name: Show version information
    shell: bash
    run: rustup toolchain list
```

The last step prints:

```
stable-x86_64-unknown-linux-gnu (default)
```

Am I doing anything wrong? Thank you so much!

Full run log: [here](https://github.com/kkew3/jieba.vim/actions/runs/13600598213/job/38025836857?pr=29)
