### ISSUE TITLE
Regression: `cargo` provided by this action fails to automatically install `rustfmt` when executing `cargo fmt` with a `rust-toolchain` file

### ISSUE THREAD

**Issue by KSXGitHub** [dtolnay/rust-toolchain#153]
## Steps to reproduce

> [!NOTE]
> I haven't actually verify this because I'm sleepy while writing this issue. If the steps fail to reproduce, let me know to fix it.

```yaml
    steps:
      - name: Create the rust-toolchain file
        run: echo 1.85.0 > rust-toolchain        
       
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check format
        run: cargo fmt --check 
```

## Current workaround

I replaced the action with the following code:

```sh
curl curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/install-rustup
chmod +x /tmp/install-rustup
/tmp/install-rustup --profile default -y
```
