### ISSUE TITLE
`default` vs `override`

### ISSUE THREAD

**Issue by max-sixty** [dtolnay/rust-toolchain#29]
Thanks for making this!

It looks like you don't want to support `rust-toolchain.toml` files from https://github.com/dtolnay/rust-toolchain/issues/12

Even if you don't, what do you think about using `override` (e.g.  `rustup override set nightly`)rather than `default`? Currently if someone has a `rust-toolchain.toml` file, the current command will not have an effect; e.g., from [here](https://github.com/prql/prql/actions/runs/3071057641/jobs/4961411375):

```
  rustup default nightly-2022-07-26
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
info: using existing install for 'nightly-2022-07-26-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-2022-07-26-x86_64-unknown-linux-gnu'

  nightly-2022-07-26-x86_64-unknown-linux-gnu unchanged - rustc 1.64.0-nightly (6dbae3ad1 2022-07-25)

info: note that the toolchain '1.62.1-x86_64-unknown-linux-gnu' is currently in use (overridden by '/home/runner/work/prql/prql/rust-toolchain.toml')
```

(fwiw, we use `rust-toolchain.toml` enthusiastically in PRQL, and find it great, particularly for reducing boilerplate, but obviously don't have full context and it's your successful tool!)

**Comment by hustcer** [comment]
+1 for override feature

**Comment by ralexstokes** [comment]
I had a similar issue and just manually parsed the toolchain file to use in this Github Action.

You can see my solution here: https://github.com/ralexstokes/ethereum-consensus/blob/main/.github/workflows/ci.yml#L16-L26

**Comment by dtolnay** [comment]
#53 added the installed toolchain name as an action output, so a rust-toolchain.toml can be overridden by doing:
```yaml
      - uses: dtolnay/rust-toolchain@...
        id: toolchain
      - run: cargo +${{steps.toolchain.outputs.name}} ...
# or:
      - run: rustup override set ${{steps.toolchain.outputs.name}}
      - run: cargo ...
```

**Comment by istellino-chub** [comment]
@dtolnay if I was using actions-rs/toolchain like this:
```
        name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
```
How can I replace it with your version?
