### ISSUE TITLE
Annotations from warnings

### ISSUE THREAD

**Issue by kaj** [dtolnay/rust-toolchain#44]
Hi!  Thanks for providing nice access to rust toolchains in github actions!

I used to use the (now unmaintained) `actions-rs/toolchain@v1` and `actions-rs/cargo@v1`, and got used to having those annotate my PR:s with any compiler / clippy warnings.  For some reasong that does not seem to happen when using this action.

My first suspision was that the color output (since #36) was to blame, but that does not seem to be the case.

My clippy job spec currently looks like this:

```yml
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all-features --color=never
```

I can't seem to find anything in [action-rs/cargo](https://github.com/actions-rs/cargo) (or [action-rs/core](https://github.com/actions-rs/core)) that explicitly parses the compiler output or creates github notifications, so I don't really know what was going on when I got those notifications vs. now that I don't.  Maybe I should just pipe my run command to something magic?
