### ISSUE TITLE
Wrong default toolchain

### ISSUE THREAD

**Issue by jschwe** [dtolnay/rust-toolchain#46]
Assuming the following input:

```
      name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        targets: x86_64-pc-windows-gnu
```

The following line

https://github.com/dtolnay/rust-toolchain/blob/e645b0cf01249a964ec099494d38d2da0f0b349f/action.yml#L72

runs e.g. `rustup default stable`, but this is incorrect on windows if previously there was already a different stable toolchain (`stable-x86_64-pc-windows-msvc`) installed (as is the case in github actions). The default toolchain after the action has run will still be the one with `msvc` abi, which is likely not what most github actions users would expect.

Since the action does allow multiple targets to be installed, I'm not sure how best to fix this.
