### ISSUE TITLE
The `set-output` command warning deprecation still exists

### ISSUE THREAD

**Issue by azzamsa** [dtolnay/rust-toolchain#48]
Hi.

After #34 has been merged, why I still get the warning?

![image](https://user-images.githubusercontent.com/17734314/207765928-b55b130b-f8f5-425e-9908-f3e23e619304.png)

https://github.com/azzamsa/nrot/actions/runs/3700796573/jobs/6269541470#step:3:19

```yml
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          # nightly is only use for rustfmt
          toolchain: nightly
          components: clippy, rustfmt
```

Am I missing something?

Thanks a lot for `rust-toolchain`! :heart:
