### ISSUE TITLE
Install musl-gcc if target is musl

### ISSUE THREAD

**Issue by hoijui** [dtolnay/rust-toolchain#49]
with `actions-rs/toolchain@v1`, `musl-gcc` seems to have been present.

With this, it is missing:

```
    strategy:
      matrix:
        build: [linux]
        include:
        - build: linux
          os: ubuntu-20.04
          rust: nightly
          target: x86_64-unknown-linux-musl

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
```

I might be missing something else, though.
