### ISSUE TITLE
Add functionality to use MSRV from rust-version field

### ISSUE THREAD

**Issue by xfix** [dtolnay/rust-toolchain#70]
It would be useful if `rust-toolchain` could use whatever version is provided in `rust-version` field in Cargo.toml. For example, it could look like this:

```yaml
- uses: dtolnay/rust-toolchain@msrv
  working-directory: project-within-workspace
```

**Comment by dtolnay** [comment]
I would prefer not to support this.

**Comment by alerque** [comment]
Can we ask why or for a re-consider? Obviously this might not be the default, but having some option to use the MSRV toolchain specified in the Cargo would add some consistency to CI runs that specifically test whether the named MSRV is working. Having to maintain the same version in two places to test it is not ideal. For example I just saw this come up here:

https://github.com/typst/typst/pull/1402#issuecomment-1575491942

**Comment by tamird** [comment]
A reasonable workaround:
```yaml
      - name: Read crate metadata
        id: metadata
        run: echo "rust-version=$(sed -ne 's/rust-version *= *\"\(.*\)\"/\1/p' Cargo.toml)" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.metadata.outputs.rust-version }}
```
